### ISSUE TITLE
deserializing error when using get_user_list function

### ISSUE THREAD

**Issue by Jayko001** [DarrenBaldwin07/clerk-rs#13]
The function get_user_list returns <Vec<crate::models::User> as seen [here](https://docs.rs/clerk-rs/latest/src/clerk_rs/apis/users_api.rs.html#375-562).
This is the User struct - https://docs.rs/clerk-rs/latest/clerk_rs/models/user/struct.User.html
However in clerk backend documentation, this is the response [schema](https://clerk.com/docs/reference/backend-api/tag/Users#operation/GetUserList).
On comparison, i found that the User struct in clerk_rs does not have the following fields

- image_url
- has_image
- primary_web3_wallet_id
- saml_accounts
- delete_self_enabled
- create_organization_enabled

**Comment by DarrenBaldwin07** [comment]
Looks like we need to bring our openAPI spec back into sync with Clerk's - adding this to the next release but also open to PRs :)
