### ISSUE TITLE
Timestamps should be `i64` and not `i32`

### ISSUE THREAD

**Issue by TmLev** [DarrenBaldwin07/clerk-rs#23]
Based on the documentation, Clerk seems to use `i64` for timestamps.

After briefly reviewing the codebase, I've identified several instances of `i32` timestamps:

* In email address verification:
   https://github.com/DarrenBaldwin07/clerk-rs/blob/b47c950a6f7b689a57d6508393b7a31b34246a1f/src/models/email_address_verification.rs#L20
* In the admin model, where it's also incorrectly wrapped in `Option` twice:
   https://github.com/DarrenBaldwin07/clerk-rs/blob/b47c950a6f7b689a57d6508393b7a31b34246a1f/src/models/admin.rs#L30
* In sign up:
   https://github.com/DarrenBaldwin07/clerk-rs/blob/b47c950a6f7b689a57d6508393b7a31b34246a1f/src/models/sign_up.rs#L101

**Comment by DarrenBaldwin07** [comment]
Great callout - PRs are welcome but Im also going to update to the latest Clerk API spec so this should fix it

**Comment by sjmiller609** [comment]
Closed by https://github.com/DarrenBaldwin07/clerk-rs/pull/31/files
