### ISSUE TITLE
Typo in API: OrganizationMembership

### ISSUE THREAD

**Issue by sjmiller609** [DarrenBaldwin07/clerk-rs#24]
[OragnizationMebership](https://docs.rs/clerk-rs/latest/clerk_rs/apis/organization_memberships_api/struct.OragnizationMebership.html#)

**Comment by DarrenBaldwin07** [comment]
Fixed via https://github.com/DarrenBaldwin07/clerk-rs/commit/70d173b75b55c5b81346ef51c38fca2c0ad4c70e
