### ISSUE TITLE
OrganizationMembership could include metadata fields

### ISSUE THREAD

**Issue by sjmiller609** [DarrenBaldwin07/clerk-rs#25]
https://docs.rs/clerk-rs/latest/clerk_rs/models/organization_membership/struct.OrganizationMembership.html

https://clerk.com/docs/reference/backend-api/tag/Organization-Memberships#operation/ListOrganizationMemberships

public_metadata | objectMetadata saved on the organization membership, accessible from both Frontend and Backend APIs
private_metadata | objectMetadata saved on the organization membership, accessible only from the Backend API

**Comment by DarrenBaldwin07** [comment]
Look like this already exists so closing
