### ISSUE TITLE
Feature flag for rustls/native-tls

### ISSUE THREAD

**Issue by jonaro00** [DarrenBaldwin07/clerk-rs#33]
The current default feature on `reqwest` uses native TLS which is harder to compile on some platforms.

It could either be switched to use rustls by default with a flag for native, or simply a flag for enabling rustls.

**Comment by DarrenBaldwin07** [comment]
Happy to accept a PR for this. I'm fun with just configuring it to use `rustls` by default

```
reqwest = { 
    version = "version", 
    features = ["rustls-tls"], 
    default-features = false 
}
```
