### ISSUE TITLE
azp claim should be optional

### ISSUE THREAD

**Issue by hazelmeow** [DarrenBaldwin07/clerk-rs#41]
The `azp` claim may not always exist on the Clerk JWT. From the [Clerk docs](https://clerk.com/docs/backend-requests/resources/session-tokens#default-session-claims):

> azp: authorized party - the Origin header that was included in the original Frontend API request made from the user. Most commonly, it will be the URL of the application. For example: https://example.com. **This claim could be omitted if, for privacy-related reasons, Origin is empty or null.**

This causes an error when decoding the JWT because `azp` is required in `ClerkJwt`: ``Error(Json(Error("missing field `azp`", line: 1, column: 185)))``.

**Comment by DarrenBaldwin07** [comment]
Closed via https://github.com/DarrenBaldwin07/clerk-rs/commit/122765a1f14d95a2349ab203ed886c3c19e1dd97
